### ISSUE TITLE
Logo glow offset from the quake ring

### ISSUE THREAD

**Issue by JenniferPylko** [antzucaro/rethink#10]
If you look closely, the blue glow is slightly to the right of the quake ring. I attached an approximate trace of the glow. I'm also not sure if this is an issue with the new website, or I just didn't notice it on the old one. I know for certain this isn't present in the svg file that comes with xonotic.
![xonotic-logo](https://cloud.githubusercontent.com/assets/3450413/6051303/e83271ec-ac94-11e4-9fd1-d05a37017eea.png)

**Comment by antzucaro** [comment]
Yes, you're right! Good catch. I believe I missed a layer when I was centering the image on the ring for alignment purposes.
