### ISSUE TITLE
Missing RSS feed

### ISSUE THREAD

**Issue by craigmaloney** [antzucaro/rethink#5]
The redesign of the Xonotic blog removed the RSS feed. Please generate a RSS feed for the postings.

Thanks!

**Comment by antzucaro** [comment]
The RSS feed for posts is [here](http://xonotic.org/index.xml). It is shown with an RSS icon in the social section. I verified this works via Feedly.com (my RSS reader).

**Comment by craigmaloney** [comment]
Cool. Would it be possible to put this more front-and-center. (eg: Adding a <link rel="alternate" type="application/rss+xml" title="... to the header?

**Comment by antzucaro** [comment]
Sure! I'll see what I can do.
