### ISSUE TITLE
The png logo is too big

### ISSUE THREAD

**Issue by dimaursu** [antzucaro/rethink#6]
It takes about 4s download on my computer, and it renders slowly. You can cut the size in 4, just by using pngquant: http://i.imgur.com/CEmVOzE.png - 48K vs 192K

**Comment by antzucaro** [comment]
I'll compress it with optipng when I get the chance.

**Comment by antzucaro** [comment]
Optipng doesn't do lossy, apparently. Thanks for the pngquanted version!

**Comment by antzucaro** [comment]
I had to replace the image due to the center ring being off, so this increased the size again. pngquant segfaults on my installation. Would you mind running it again on the fixed image?

**Comment by dimaursu** [comment]
http://i.imgur.com/q7MaXzU.png here you go. Back to 47K
